version: '3.8'

services:
  product-db:
    image: postgres:latest
    container_name: product-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product-db
    ports:
      - "5433:5432"